module.exports = {
    app: 'afs/',
    dist: 'www/',
    test: 'afs/test/',
    scss: 'afs/scss/',
    sassSrc: 'afs/scss/**/*.{scss,sass}',
    sassVendor: 'afs/scss/vendor.scss',
    cssDir: 'afs/content/css',
    bower: 'afs/bower_components/',
    tmp: 'www/tmp',
    revManifest: 'www/tmp/rev-manifest.json',
    port: 9000,
    liveReloadPort: 35729,
    uri: 'http://localhost:',
    constantTemplate: '(function () {\n' +
    '    \'use strict\';\n' +
    '    // DO NOT EDIT THIS FILE, EDIT THE GULP TASK NGCONSTANT SETTINGS INSTEAD WHICH GENERATES THIS FILE\n' +
    '    angular\n' +
    '        .module(\'<%- moduleName %>\')\n' +
    '<% constants.forEach(function(constant) { %>        .constant(\'<%- constant.name %>\', <%= constant.value %>)\n<% }) %>;\n' +
    '})();\n'
};
